.\"
.\" $Id: nemesis-ospf.1,v 1.2 2003/11/09 10:21:00 jnathan Exp $
.\"
.\" THE NEMESIS PROJECT
.\" Copyright (C) 1999, 2000 Mark Grimes <mark@stateful.net>
.\" Copyright (C) 2001 - 2003 Jeff Nathan <jeff@snort.org>
.\" 
.TH NEMESIS-OSPF 1 "2 May 2018" 
.SH NAME
nemesis-ospf \- OSPF Protocol (The Nemesis Project)
.SH SYNOPSIS
\fBnemesis\-ospf\fP [\-vZ] [\fIoptlist\fP] 
.SH DESCRIPTION
.B The Nemesis Project
is designed to be a command line-based, portable human IP stack for UNIX-like
and Windows systems.  The suite is broken down by protocol, and should allow
for useful scripting of injected packets from simple shell scripts.
.SS OSPF Packet Types
.TP
\fB\-p\fP \fITYPE (\-pH, \-pD, \-pR, \-pU, \-pA)\fR
Hello (\-pH), Database Description (\-pD), 
Link State Request (\-pR),
Link State Update (\-pU),
Router Links Advertisement (\-pUR),
Network Links Advertisement (\-pUN),
IP Summary Links Advertisement (\-pUS),
AS External Link Advertisement (\-pUE),
.SS OSPF HELLO options
.TP
\fB-N\fP \fIADDR\fR
Neighbor Router Address
.TP
\fB-i\fP \fISEC\fR
Dead Router Interval, seconds
.TP
\fB-l\fP \fISEC\fR
OSPF Interval, seconds
.SS OSPF Database Description (DBD) options
.TP
\fB-z\fP \fILEN\fR
OSPF Maximum Datagram Length
.TP
\fB-x\fP \fITYPE\fR
OSPF DBD Exchange Type
.SS OSPF Link State Update (LSU) options
.TP
\fB-B\fP \fINUM\fR
Number of Link State Advertisements (LSAs) to broadcast
.TP
\fB-P\fP \fIFILE\fR
RAW payload file with LSAs, in plain \-pU mode
.SS OSPF Router LSA options
\fB-L\fP \fIADDR\fR
Link State ID: Originating Router ID (IP address)
.TP
\fB-u\fP \fINUM\fR
Number of links, default 1
.TP
\fB-j\fP \fIADDR\fR
Link ID
.TP
\fB-k\fP \fIDATA\fR
Link data
.TP
\fB-y\fP \fITYPE\fR
Link type, default 1
.TP
\fB-w\fP \fITOS\fR
Link TOS number, default 0
.TP
\fB-m\fP \fIMETRIC\fR
Link TOS (0) metric (2 bytes)
.SS OSPF Autonomous System External LSA options
\fB-f\fP \fIADDR\fR
Forward Address
.TP
\fB-g\fP \fITAG\fR
External route tag
.SS OSPF Network LSA options
\fB-L\fP \fIADDR\fR
Link State ID: Originating Router ID (IP address)
.TP
\fB-n\fP \fIMASK\fR
Netmask
.TP
\fB-h\fP \fIADDR\fR
Attached Router (IP address)
.SS OSPF Summary LSA (IP Network) options
\fB-L\fP \fIADDR\fR
Link State ID: Network route to summarize
.TP
\fB-n\fP \fIMASK\fR
Netmask of route
.TP
\fB-c\fP \fINUM\fR
Cost of this route (4 bytes)
.SS Generic LSA options for LSR and LSU packets
\fB-G\fP \fILSA Age\fR
Link State Advertisement Age.
.TP
\fB-L\fP \fIADDR\fR
Link State ID, usually the Router ID of the originating router
.TP
\fB-r\fP \fIADDR\fR
Advertising Router Address
.TP
\fB-s\fP \fINUM\fR
Sequence Number
.TP
\fB-n\fP \fIMASK\fR
Multi-purpose netmask
.SS OSPF options
\fB-m\fP \fIMETRIC\fR
OSPF Metric
.TP
\fB-s\fP \fINUM\fR
OSPF Sequence Number 
.TP
\fB-r\fP \fIADDR\fR
OSPF Advertising Router Address
.TP
\fB-n\fP \fIMASK\fR
OSPF Netmask
.TP
\fB-o\fP \fIOPT\fR
OSPF Options, 1 byte value
.TP
\fB-R\fP \fIADDR\fR
OSPF Source Router ID
.TP
\fB-A\fP \fIADDR\fR
OSPF Area ID, e.g. 0.0.0.1, default 0.0.0.0
.TP
\fB-P\fP \fIFILE\fR
Filename to read for raw (HEX) OSPF packet payload, appended after
selected packet type.  I.e., can be used with \-pU to create multi LSA
Link State Updates.
.TP
.IP "-v"
Display the injected packet in human readable form.  Use twice to see a hexdump
of the injected package with printable ASCII characters on the right.  Use three
times for a hexdump without decoded ASCII.
.SH IP OPTIONS
.IP "-S ADDR"
Specify the source address within the IP header.
.IP "-D ADDR"
Specify the destination address within the IP header.  Defaults to the
link-local multicast address 224.0.0.5 (All OSPF Routers).
.IP "-F OPT"
Specify the IP header fragmentation options:

.in +.51
.nf
.I -FD (don't fragment)
.I -FM (more fragments)
.I -FR (reserved flag)
.I -F <offset>
.fi
.in -.51

IP fragmentation options can be specified individually or combined into
a single argument to the \-F command line switch by separating the
options with commas (eg. '\-FD,M') or spaces (eg. '\-FM 223').  The IP
fragmentation offset is a 13-bit field with valid values from 0 to 8189.
Don't fragment (DF), more fragments (MF) and the reserved flag (RESERVED
or RB) are 1-bit fields.

NOTE: Under normal conditions, the reserved flag is unset.
.IP "-I ID"
Specify the
.I ID
within the IP header.
.IP "-O FILE"
This will cause nemesis-ospf to use the specified raw (HEX)
.I FILE
as the options when building the IP header for the injected packet.  IP
options can be up to 40 bytes in length.  The IP options file must be
created manually based upon the desired options.  IP options can also be
read from stdin by specifying '\-O \-' instead of a file.
.IP "-t TOS"
within the IP header.  Valid type of service values:

.in +.51
.nf
2  (Minimize monetary cost)
4  (Maximize reliability)
8  (Maximize throughput)
24 (Minimize delay)
.fi
.in -.51

NOTE: Under normal conditions, only one type of service is set within a 
packet.  To specify multiple types, specify the sum of the desired values as
the type of service.
.IP "-T TTL"
Specify the TTL value within the IP header.  This defaults to 1 since
the default destination IP address is a link-local multicast address.
.SH DATA LINK OPTIONS
.IP "-d <NAME|NUM>"
Specify the interface name, for UNIX-like systems, or number for Windows systems,
of the Ethernet device to use (eg. fxp0, eth0, hme0, 1).
.IP "-H MAC"
Specify the source MAC address, XX:XX:XX:XX:XX:XX
.IP "-M MAC"
Specify the destintion MAC address, XX:XX:XX:XX:XX:XX
.IP "-Z"
Lists available network interfaces by number for use in link-layer 
injection.

NOTE: This feature is only relevant to Windows systems.
.SH DIAGNOSTICS
Nemesis-ospf returns 0 on a successful exit, 1 if it exits on an error.
.SH BUGS
Please report at https://github.com/troglobit/nemesis/issues
.SH "AUTHOR"
Mark Grimes <mark@stateful.net> and Jeff Nathan <jeff@snort.org>
.SH "SEE ALSO"
.BR "nemesis-arp(1), nemesis-dns(1), nemesis-ethernet(1), nemesis-icmp(1), "
.BR "nemesis-igmp(1), nemesis-ip(1), nemesis-rip(1), nemesis-tcp(1), "
.BR "nemesis-udp(1)"
