.\"
.\" $Id: nemesis-tcp.1,v 1.3 2004/10/07 01:20:56 jnathan Exp $
.\"
.\" THE NEMESIS PROJECT
.\" Copyright (C) 1999, 2000 Mark Grimes <mark@stateful.net>
.\" Copyright (C) 2001 - 2003 Jeff Nathan <jeff@snort.org>
.\"
.TH NEMESIS-TCP 1 "16 May 2003" 
.SH NAME
nemesis-tcp \- TCP Protocol (The Nemesis Project)
.SH SYNOPSIS
nemesis-tcp [-vZ?] [-a
.I ack-number
.B ] [-d
.I Ethernet-device
.B ] [-D
.I destination-IP-address
.B ] [-f
.I TCP-flags
.B ] [-F
.I fragmentation-options
.B ] [-I
.I IP-ID
.B ] [-M
.I destination-MAC-address
.B ] [-o
.I TCP-options-file
.B ] [-O
.I IP-options-file
.B ] [-P
.I payload-file
.B ] [-s
.I sequence-number
.B ] [-S
.I source-IP-address
.B ] [-t
.I IP-TOS
.B ] [-T
.I IP-TTL
.B ] [-u
.I urgent-pointer
.B ] [-w
.I window-size
.B ] [-x
.I source-port
.B ] [-y
.I destination-port
.B ]
.SH DESCRIPTION
.B The Nemesis Project
is designed to be a command line-based, portable human IP stack for UNIX-like 
and Windows systems.  The suite is broken down by protocol, and should allow 
for useful scripting of injected packets from simple shell scripts. 
.PP
.B nemesis-tcp
provides an interface to craft and inject TCP packets allowing the user to 
specify any portion of a TCP packet as well as lower-level IP packet
information.
.SH TCP Options
.IP "-a Acknowledgement-Number"
Specify the
.I acknowledgement-number (ACK number)
within the TCP header.
.IP "-f TCP flags (-fS/-fA/-fR/-fP/-fF/-fU/-fE/-fC/-f-)"
Specify the
.I TCP flags:

.in +.51
.nf
.I -fS (SYN)
.I -fA (ACK)
.I -fR (RST)
.I -fP (PSH)
.I -fF (FIN)
.I -fU (URG)
.I -fE (ECE)
.I -fC (CWR)
.I -f- NONE
.fi
.in -.51

within the TCP header.  Flags can be combined in the form '-fPA'.  If flags 
are specified in the form '-f-' then the TCP header will be built without 
flags.
.IP "-o TCP-options-file"
This will cause nemesis-dns to use the specified
.I TCP-options-file
as the options when building the TCP header for the injected packet.  TCP
options can be up to 40 bytes in length.  The TCP options file must be created
manually based upon the desired options.  TCP options can also be read from
stdin by specifying '-o -' instead of a TCP-options-file.
.IP "-P payload-file"
This will case nemesis-tcp to use the specified
.I payload-file
as the payload when injecting TCP packets.  For packets injected using the
raw interface (where -d is not used), the maximum payload size is
65415 bytes.  For packets injected using the link layer interface
(where -d IS used), the maximum payload size is 1380 bytes.  Payloads can also
be read from stdin by specifying '-P -' instead of a payload file.

Windows systems are limited to a maximum payload size of 1380 bytes for TCP
packets.
.IP "-s sequence-number"
Specify the
.I sequence-number
within the TCP header.
.IP "-u urgent-pointer-offset"
Specify the
.I urgent-pointer-offset
within the TCP header.
.IP "-v verbose-mode"
Display the injected packet in human readable form.  Use twice to see a hexdump
of the injected packet with printable ASCII characters on the right.  Use three
times for a hexdump without decided ASCII.
.IP "-w window-size"
Specify the
.I window-size
within the TCP header.
.IP "-x source-port"
Specify the
.I source-port
packet within the TCP header.
.IP "-y destination port"
Specify the
.I destintion-port
within the TCP header.
.SH IP OPTIONS
.IP "-D destination-IP-address"
Specify the
.I destination-IP-address
within the IP header.
.IP "-F fragmentation-options (-F[D],[M],[R],[offset])"
Specify the
.I fragmentation options:

.in +.51
.nf
.I -FD (don't fragment)
.I -FM (more fragments)
.I -FR (reserved flag)
.I -F <offset>
.fi
.in -.51

within the IP header.  IP fragmentation options can be specified individually 
or combined into a single argument to the -F command line switch by separating 
the options with commas (eg. '-FD,M') or spaces (eg. '-FM 223').  The IP 
fragmentation offset is a 13-bit field with valid values from 0 to 8189.  
Don't fragment (DF), more fragments (MF) and the reserved flag (RESERVED or RB) 
are 1-bit fields.  

NOTE: Under normal conditions, the reserved flag is unset.
.IP "-I IP-ID"
Specify the
.I IP-ID
within the IP header.
.IP "-O IP-options-file"
This will cause nemesis-tcp to use the specified
.I IP-options-file
as the options when building the IP header for the injected packet.  IP 
options can be up to 40 bytes in length.  The IP options file must be created
manually based upon the desired options.  IP options can also be read from 
stdin by specifying '-O -' instead of an IP-options-file.
.IP "-S source-IP-address"
Specify the
.I source-IP-address
within the IP header.
.IP "-t IP-TOS"
Specify the
.I IP-type-of-service (TOS)
within the IP header.  Valid type of service values:

.in +.51
.nf
2  (Minimize monetary cost)
4  (Maximize reliability)
8  (Maximize throughput)
24 (Minimize delay)
.fi
.in -.51

NOTE: Under normal conditions, only one type of service is set within a 
packet.  To specify multiple types, specify the sum of the desired values as
the type of service.
.IP "-T IP-TTL"
Specify the
.I IP-time-to-live (TTL)
within the IP header.
.SH DATA LINK OPTIONS
.IP "-d Ethernet-device"
Specify the name (for UNIX-like systems) or the number (for Windows systems) 
of the
.I Ethernet-device
to use (eg. fxp0, eth0, hem0, 1).
.IP "-H source-MAC-address"
Specify the
.I source-MAC-address
(XX:XX:XX:XX:XX:XX).
.IP "-M destination-MAC-address"
Specify the
.I defination-MAC-address
(XX:XX:XX:XX:XX:XX).
.IP "-Z list-network-interfaces"
Lists the available network interfaces by number for use in link-layer 
injection.

NOTE: This feature is only relevant to Windows systems.
.SH DIAGNOSTICS
Nemesis-tcp returns 0 on a successful exit, 1 if it exits on an error.
.SH BUGS
Send concise and clearly written bug reports to jeff@snort.org
.SH "AUTHOR"
Jeff Nathan <jeff@snorg.org>

Originally developed by Mark Grimes <mark@stateful.net>
.SH "SEE ALSO"
.BR "nemesis-arp(1), nemesis-dns(1), nemesis-ethernet(1), nemesis-icmp(1), "
.BR "nemesis-igmp(1), nemesis-ip(1), nemesis-ospf(1), nemesis-rip(1), "
.BR "nemesis-udp(1)"
