.\" THE NEMESIS PROJECT
.\" Copyright (C) 1999, 2000, 2001 Mark Grimes <mark@stateful.net>
.\" Copyright (C) 2001 - 2003 Jeff Nathan <jeff@snort.org>
.\" Copyright (C) 2019 Joachim Nilsson <troglobit@gmail.com>
.\"
.Dd Nov 24, 2019
.Dt nemesis-arp 1
.Sh NAME
.Nm nemesis-arp
.Nd ARP/RARP Protocol (The Nemesis Project)
.Sh SYNOPSIS
.Nm
.Op Fl rsTRvZ?
.Op Fl d Ar IFNAME
.Op Fl D Ar ADDR
.Op Fl h Ar MAC
.Op Fl H Ar MAC
.Op Fl m Ar MAC
.Op Fl M Ar MAC
.Op Fl P Ar FILE
.Op Fl S Ar ADDR
.Sh DESCRIPTION
.Nm nemesis
is designed to be a command line-based, portable human IP stack for UNIX-like 
and Windows systems.  The suite is broken down by protocol, and should allow 
for useful scripting of injected packets from simple shell scripts. 
.Pp
.Nm
provides an interface to craft and inject ARP frames allowing the user to 
specify any portion of an ARP frame. 
.Sh ARP/RARP OPTIONS
.Bl -tag -width Ds
.It Fl D Ar ADDR
Specify the destination IP address of the injected ARP frame.
.It Fl h Ar MAC
Specify the sender hardware address within the ARP frame only.
.It Fl m Ar MAC
Specify the target hardware address within the ARP frame only.
.It Fl P Ar FILE
This will cause
.Nm
to use the specified payload
.Ar FILE
as the payload when injecting ARP/RARP frames.  The maximum payload size is 
1472 bytes in order to account for the maximum Ethernet frame size.  Payloads
can also be read from stdin by specifying
.Fl P-
instead.
.It Fl r
Enables ARP/RARP replies.
.It Fl R
Enables RARP mode.
.It Fl s
When performing ARP requests, rather than zero out the 6 byte target hardware 
address field within the ARP frame, Solaris systems copy the target hardware 
address from the Ethernet header into this field.  This option emulates Solaris
systems by setting the target hardware address within ARP frame to 
ff:ff:ff:ff:ff:ff rather than the standard 00:00:00:00:00:00.
.It Fl S Ar ADDR
Specify the source IP address of the injected ARP frame.
.It Fl v
Display the injected packet in human readable form.  Use twice to see a hexdump
of the injected packet with printable ASCII characters on the right.  Use three 
times for a hexdump without decoded ASCII.
.El
.Sh DATA LINK OPTIONS
.Bl -tag -width Ds
.It Fl d Ar IFNAME
Specify the name (for UNIX-like systems) or the number (for Windows systems) 
of the
.Ar IFNAME
to use (eg. fxp0, eth0, hme0, 1).
.It Fl H Ar MAC
Specify the source MAC address
.Ar ( XX:XX:XX:XX:XX:XX ) .
.It Fl M Ar MAC
Specify the destintion MAC address
.Ar ( XX:XX:XX:XX:XX:XX ) .
.It Fl Z
Lists the available network interfaces by number for use in link-layer 
injection.
.Pp
.Sy NOTE:
This feature is only relevant to Windows systems.
.El
.Sh DIAGNOSTICS
.Nm
returns 0 on a successful exit, 1 if it exits on an error.
.Sh SEE ALSO
.Xr nemesis-dhcp 1 ,
.Xr nemesis-dns 1 ,
.Xr nemesis-ethernet 1 ,
.Xr nemesis-icmp 1 ,
.Xr nemesis-igmp 1 ,
.Xr nemesis-ip 1 ,
.Xr nemesis-ospf 1 ,
.Xr nemesis-rip 1 ,
.Xr nemesis-tcp 1 ,
.Xr nemesis-udp 1 .
.Sh AUTHORS
.An Mark Grimes Aq Mt mark@stateful.net
and
.An Jeff Nathan Aq Mt jeff@snort.org .
.Sh BUGS
Please report at
.Lk https://github.com/libnet/nemesis/issues
