.\" THE NEMESIS PROJECT
.\" Copyright (C) 1999, 2000 , 2001 Mark Grimes <mark@stateful.net>
.\" Copyright (C) 2001 - 2003 Jeff Nathan <jeff@snort.org>
.\" Copyright (C) 2019 Joachim Nilsson <troglobit@gmail.com>
.\"
.Dd Nov 21, 2019
.Dt nemesis-dhcp 1 USM
.Sh NAME
.Nm nemesis-dhcp
.Nd DHCP Protocol (The Nemesis Project)
.Sh SYNOPSIS
.Nm
.Op Fl vZ?
.Op Fl c Ar COUNT
.Op Fl i Ar INTERVAL
.Op Fl d Ar IFNAME
.Op Fl C Ar ADDR
.Op Fl D Ar ADDR
.Op Fl F Ar OPT
.Op Fl f Ar FLAGS
.Op Fl g Ar ADDR
.Op Fl h Ar MAC
.Op Fl H Ar MAC
.Op Fl I Ar ID
.Op Fl M Ar MAC
.Op Fl o Ar CODE
.Op Fl O Ar FILE
.Op Fl P Ar FILE
.Op Fl s Ar ADDR
.Op Fl S Ar ADDR
.Op Fl t Ar IP-TOS
.Op Fl T Ar TTL
.Op Fl x Ar PORT
.Op Fl y Ar PORT
.Op Fl Y Ar ADDR
.Sh DESCRIPTION
.Nm nemesis
is designed to be a command line-based, portable human IP stack for UNIX-like 
and Windows systems.  The suite is broken down by protocol, and should allow 
for useful scripting of injected packets from simple shell scripts. 
.Pp
.Nm
provides an interface to craft and inject DHCP packets allowing the user to 
specify any portion of a DHCP packet as well as lower-level IP and TCP/UDP 
packet information.
.Pp
By default a DHCP Discover (client) message is created.  To successfully
send it out a network interface you must be root.
.Sh GENERAL OPTIONS
.Bl -tag -width Ds
.It Fl c Ar COUNT
Number of packets to send, default: 1.
.It Fl i Ar INTERVAL
Seconds between repeatedly sent packets, only available if
.Fl c
is given.
.It Fl v
Display the injected packet in human readable form.  Use twice to see a hexdump
of the injected packet with printable ASCII characters on the right.  Use three
times for a hexdump without decoded ASCII.
.El
.Sh DHCP OPTIONS
.Bl -tag -width Ds
.It Fl o Ar CODE
BOOTP/DHCP opcode to send, default: 1 (request).
.It Fl f Ar FLAGS
Specify the
.Ar FLAGS
within the DHCP header, default: 0x8000.
.It Fl g Ar ADDR
DHCP Gateway (relay agent) IP address.
.It Fl s Ar ADDR
DHCP server IP address.
.It Fl C Ar ADDR
DHCP client's IP address.
.It Fl Y Ar ADDR
Your IP address, the lease from the DHCP server.
.It Fl h Ar MAC
Client's HW address, MAC.
.It Fl P Ar FILE
This will cause
.Nm
to use the specified
.Ar FILE
as the payload when injecting DHCP packets.  For packets injected using
the raw interface (where
.Fl d
is not used), the maximum payload size is 65455 for DHCP packets.  For
packets injected using the link layer interface (where
.Fl d
IS used), the maximum payload size is 1420 bytes.  Payloads can also be
read from stdin by specifying
.Fl P-
instead.
.Pp
The payload file can consist of any arbitrary data though it will be
most useful to create a payload resembling the structure of the DHCP
packet specified using the command-line options.
.Pp
.Sy NOTE:
Windows systems are limited to a maximum payload size of 1420 bytes.
.El
.Sh UDP OPTIONS
.Bl -tag -width Ds
.It Fl x Ar PORT
UDP source port of injected packet.
.It Fl y Ar PORT
UDP target port of injected packet.
.El
.Sh IP OPTIONS
.Bl -tag -width Ds
.It Fl D Ar ADDR
Specify the destination IP address in the IP header.
.It Fl F Ar OPT
Specify the fragmentation options in the IP header:
.Pp
.Bl -tag -width "-F offset" -compact -offset indent
.It Fl FD
don't fragment
.It Fl FM
more fragments
.It Fl FR
reserved flag
.It Fl F Ar offset
.El
.Pp
IP fragmentation options can be specified individually or combined into
a single argument to the
.Fl F
command line switch by separating the options with commas (eg.
.Fl FD,M )
or spaces (eg.
.Fl FM Ar 223 ) .
The IP fragmentation offset is a 13-bit field with valid values from 0
to 8189.  Don't fragment (DF), more fragments (MF) and the reserved flag
(RESERVED or RB) are 1-bit fields.
.Pp
.Sy NOTE:
Under normal conditions, the reserved flag is unset.
.It Fl I Ar ID
Specify the IP ID in the IP header.
.It Fl O Ar FILE
This will cause
.Nm
to use the specified IP options file,
.Ar FILE ,
as the options when building the IP header for the injected packet.  IP
options can be up to 40 bytes in length.  The IP options file must be
created manually based upon the desired options.  IP options can also be
read from stdin by specifying
.Fl O-
instead of an IP options file.
.It Fl S Ar ADDR
Specify the source IP address in the IP header.
.It Fl t Ar TOS
Specify the IP type-of-service (TOS) in the IP header.  Valid type
of service values:
.Pp
.Bl -tag -width 24 -offset indent -compact
.It 2
Minimize monetary cost
.It 4
Maximize reliability
.It 8
Maximize throughput
.It 24
Minimize delay
.El
.Pp
.Sy NOTE:
Under normal conditions, only one type of service is set within a
packet.  To specify multiple types, specify the sum of the desired
values as the type of service.
.It Fl T Ar TTL
Specify the IP time-to-live (TTL) in the IP header.
.El
.Sh DATA LINK OPTIONS
.Bl -tag -width Ds
.It Fl d Ar IFNAME
Specify the name (for UNIX-like systems) or the number (for Windows systems) 
of the
.Ar IFNAME
to use (eg. fxp0, eth0, hme0, 1).
.It Fl H Ar MAC
Specify the source
.Ar MAC
address,
.Ar ( XX:XX:XX:XX:XX:XX ) .
.It Fl M Ar MAC
Specify the destination
.Ar MAC
address,
.Ar ( XX:XX:XX:XX:XX:XX ) .
.It Fl Z
Lists the available network interfaces by number for use in link-layer 
injection.
.Pp
.Sy NOTE:
This feature is only relevant to Windows systems.
.El
.Sh DIAGNOSTICS
.Nm
returns 0 on a successful exit, 1 if it exits on an error.
.Sh SEE ALSO
.Xr nemesis-arp 1 ,
.Xr nemesis-dns 1 ,
.Xr nemesis-ethernet 1 ,
.Xr nemesis-icmp 1 ,
.Xr nemesis-igmp 1 ,
.Xr nemesis-ip 1 ,
.Xr nemesis-ospf 1 ,
.Xr nemesis-rip 1 ,
.Xr nemesis-tcp 1 ,
.Xr nemesis-udp 1 .
.Sh AUTHORS
.An Joachim Nilsson Aq Mt troglobit@gmail.com
.Sh BUGS
Please report at
.Lk https://github.com/libnet/nemesis/issues
